### PR TITLE
document how to create slack bot

### PR DESCRIPTION
**Pull request by martinklepsch**
This explicitly documents how to get the required slackbot token. Since Slack apps can also provide bot users there are two ways to do things. This documents that we use the "Custom Integration" way (which is coupled to a workspace) vs the "Slack App" way (which can be added to multiple workspaces).

### CODE REVIEW

**Comment by martinklepsch** [comment]
Note that this mentions the `.envrc` setup which is part of #11 and not merged yet.

**Comment by PombeirP** [comment]
Thanks for the PR @martinklepsch!

**Comment by martinklepsch** [comment]
Will update this PR as per env discussion in #11.

**Comment by martinklepsch** [comment]
This now also contains the commit from #13 to make merging easier. If you merge #13 first and then rebase + merge this PR it should work without any manual conflict resolution.

**Comment by PombeirP** [comment]
Thanks @martinklepsch! Can you please fix the merge conflict and then I'll merge it in?

**Comment by martinklepsch** [comment]
done @PombeirP

**Comment by PombeirP** [comment]
Merged. Thanks again @martinklepsch!

**Pull request merged**
